# Generated by Django 2.2.7 on 2019-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
