# Generated by Django 2.2.7 on 2019-11-21 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0003_auto_20191121_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('orgs_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('avatar_url', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
